# 服务器相关配置
server:
  port: 8989
  servlet:
    context-path: /cmfz
    jsp:
      init-parameters:
        development: true
# spring相关配置
spring:
  redis:
    host: 192.168.179.132
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/buddhism?characterEncoding=UTF-8
  mvc:
    view:
      suffix: .jsp
      prefix: /
  servlet:
    multipart:
      max-file-size: 70MB
      max-request-size: 100MB

# mybatis相关配置
mybatis:
  type-aliases-package: com.baizhi.entity
  mapper-locations: classpath:com/baizhi/mapper/*Mapper.xml
# 日志
logging:
  level:
    com.baizhi.dao: debug